### PR TITLE
Update buyers' landing - index.mdx

### PR DESCRIPTION
**Pull request by rosamundtgov**
Updated based on OASIS feedback - 

**Market research -- (addition, under Complete market research)**

Title: Register in Symphony [buyers-guide/register-in-symphony/]
Description: In order to conduct RFIs, you must register in Symphony Procurement Suite.

**Prepare to develop your solicitation -- (addition, will replace Register in Symphony)**

Title: Get familiar with Symphony [resources/#proposal-submission-and-task-management]
Description: Check out our proposal submission and task management resources in preparation for developing your solicitation in Symphony Procurement Suite.

### CODE REVIEW

**Review by rosamundtgov — COMMENTED** [review]
Fixed URL -

**Review by vickimcfadden — APPROVED** [review]
lgtm

**Review by vickimcfadden — APPROVED** [review]
lgtm

**Comment by rosamundtgov** [comment]
@ekidenda @PowderD this is ready for your review: https://federalist-76c8d2ee-2655-47f7-8fa4-63811842d0a5.sites.pages.cloud.gov/demo/gsa/oasis-plus/oasis-plus/buyers-guide//

**Pull request merged**
