### PR TITLE
Update index.astro - updated O+ landing page Announcements Box

### PR DESCRIPTION
**Pull request by smteague**

### CODE REVIEW

**Comment by vickimcfadden** [comment]
@smteague should we remove this text? Also, the dates are in different formats mm/dd/yy vs month day, year. We should be consistent. 

OASIS+ Small Business Awards Announcement: July 30, 2024 - The OASIS+ Small Business announcements were published on [SAM.GOV](https://sam.gov/opp/ccc8988feb9c4823a584353dbde0b3db/view).

**Comment by smteague** [comment]
@vickimcfadden Hi Vicki, great catch on the dates. I'll fix that.  We do want to keep the reference on when they were announced (at least for now).

**Review by mark-meyer — APPROVED** [review]
This looks great to me!

**Comment by smteague** [comment]
@mark-meyer Hi Mark... can you also push this ticket live when you have a moment?  Thank you so much.

**Pull request merged**
