### PR TITLE
address AMP links issue

### PR DESCRIPTION
**Pull request by weiwang-gsa**
Address AMP issues
- removed TOC links
- address the same text with different link issue

### CODE REVIEW

**Review by mark-meyer — APPROVED** [review]
LGTM

**Review by rosamundtgov — APPROVED** [review]
Looks good -

**Comment by rosamundtgov** [comment]
I believe there are still outstanding issues; see https://github.com/GSA/oasis-plus/issues/449#issuecomment-2140779437

**Comment by rosamundtgov** [comment]
looks good to me - approved.

**Pull request merged**
